[tool.pytest]
addopts = --strict -rf --durations=0
console_output_style = count
junit_family=xunit2
markers =
    slow: Convenience marker to skip slower running tests during local development

[tool.pydocstyle]
convention = numpy

[tool.black]
line-length = 100
